### PR TITLE
Code docs in CEP47

### PR DESCRIPTION
**Pull request by hoffmannjan**

### CODE REVIEW

**Review by Buddhika-Pathirathna — APPROVED** [review]
Looks good, Thanks

**Comment by RitaMAllenCA** [comment]
@hoffmannjan @ipopescu This is OLD - do we care any more?

**Comment by ipopescu** [comment]
@RitaMAllenCA, I still think we need this because it's good information and we still need to maintain this repository (until we decide to archive it). 
@hoffmannjan why is it still in draft mode? Were you planning to do more work? Can we merge it?

**Comment by hoffmannjan** [comment]
> @RitaMAllenCA, I still think we need this because it's good information and we still need to maintain this repository (until we decide to archive it). @hoffmannjan why is it still in draft mode? Were you planning to do more work? Can we merge it?

TBH I was planning to add more, but still we can merge this and later add more :)

**Comment by RitaMAllenCA** [comment]
@Jan Hoffmann ***@***.***> @Iulia Popescu ***@***.***> looks
like it won't merge until we get an approving review, but I think Buddika
no longer works here?  I added ilulia, but this is not a high priority

**Review by ipopescu — APPROVED** [review]

**Comment by ipopescu** [comment]
@hoffmannjan, I quickly added comments for the rest of the functions in the file (based on our training materials). 
Please review, and if the explanations are correct, this PR is ready to go. Please merge it :). Thanks!

**Comment by hoffmannjan** [comment]
Looks great @ipopescu ! Merging!

**Comment by jan** [comment]
Great job guys. But wrong Jan.

**Comment by ipopescu** [comment]
Sorry! That was on me. Thanks!

**Pull request merged**
